In [2]:
1.

1.0

In [11]:
import numpy as np

In [12]:
2.

2.0

In [49]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [52]:
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [53]:
c = np.full(5, 3.14)
print(c)

[3.14 3.14 3.14 3.14 3.14]


In [71]:
d = np.array(range(21))
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [72]:
e = np.full((5,5),1)
print(e)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
3.

In [79]:
x = np.random.randn(3,3,3)
x

array([[[-1.50533104, -0.75975023, -0.62807421],
        [ 1.76439442,  0.47696066, -0.85818297],
        [-0.29171141, -0.83802655, -1.3932873 ]],

       [[ 0.54763549,  1.66794082,  0.98930087],
        [ 0.14498783,  0.13256271,  0.80172067],
        [-0.23802616,  0.31384511, -0.44145043]],

       [[-0.433824  ,  0.61580461, -0.14389311],
        [ 1.15191915,  0.59744127,  1.96697518],
        [-1.5656081 , -0.7931085 , -1.09444365]]])

In [80]:
x = np.random.randn(3,3,3).reshape(27,)
x

array([-0.98036399, -0.94046014, -0.03677251,  0.61868476,  0.21414319,
        0.1233181 ,  1.13785465, -2.16605065, -0.71771485, -0.10218712,
        0.45866753, -0.46599829,  0.58040981, -2.355427  ,  0.84249336,
       -1.93928707,  0.03993669, -0.05833515, -1.09446918, -0.52701384,
        1.25976652,  0.32015533,  0.0163514 ,  0.51588535,  1.07985873,
        1.1049267 , -0.28252808])

In [ ]:
4.

In [81]:
y = np.linspace(1,10,20)
y

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
5.

In [103]:
a = np.arange(1, 26).reshape(5, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [92]:
a[3,4]

20

In [94]:
a[1:, 3:5]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [95]:
a[1]

array([ 6,  7,  8,  9, 10])

In [98]:
a[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [99]:
a[1:3, 2:4]

array([[ 8,  9],
       [13, 14]])

In [ ]:
6.

In [106]:
a.sum()

325

In [109]:
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [ ]:
8.

In [120]:
a[a>a.mean()]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
9.

In [121]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [123]:
b.argmin()

6

In [ ]:
10.

In [124]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [131]:
from numpy import unravel_index

In [137]:
print("위치: ",unravel_index(c.argmax(),c.shape))

위치 :  (2, 1)


In [145]:
x=c.max()
print("최대값: ",(np.floor(x*100)/100))

최대값:  1.65
