In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3])

In [3]:
print(arr)

[1 2 3]


In [4]:
arr

array([1, 2, 3])

In [5]:
lst=[1,2,3,4]
lst

[1, 2, 3, 4]

In [6]:
arr=np.array(lst)
arr

array([1, 2, 3, 4])

In [7]:
arr.shape

(4,)

In [8]:
type(arr)

numpy.ndarray

In [9]:
lst=[1,'hi']
lst

[1, 'hi']

In [10]:
arr=np.array(lst)
arr

array(['1', 'hi'], dtype='<U11')

In [11]:
lst=[[1,2,3],
     [4,5,6]]
lst

[[1, 2, 3], [4, 5, 6]]

In [12]:
arr=np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
lst=[[[1,2],
      [3,4]],
    [[5,6],
     [7,8]]]
arr=np.array(lst)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
range(1,5)

range(1, 5)

In [16]:
list(range(1,5))

[1, 2, 3, 4]

In [17]:
np.arange(1,5)

array([1, 2, 3, 4])

In [18]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [19]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [21]:
np.full((3,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [30]:
arr=np.random.rand(5,2)
arr

array([[0.61293476, 0.58160332],
       [0.57589087, 0.08483   ],
       [0.84189378, 0.45192559],
       [0.09899391, 0.40457924],
       [0.61960096, 0.86031487]])

In [31]:
arr.transpose()

array([[0.61293476, 0.57589087, 0.84189378, 0.09899391, 0.61960096],
       [0.58160332, 0.08483   , 0.45192559, 0.40457924, 0.86031487]])

In [26]:
arr.mean()

0.5011140533531971